product: raise in handle_form_errors() with string args
Prior to this change, if handle_form_errors() raised a RuntimeError,
that exception's args property was a one-element tuple with a either
a string or a list of strings.

Simplify this so that exception's args property is always a tuple with
one or more error strings. This change makes the unit test assertions
easier to write.

For Ansible users reading the rails server-side errors inside the Python
backtraces, the stringify'd exceptions in backtrace looks essentially
the same.

Before:

  RuntimeError: ["Name can't be blank", "Short name can't be blank"]

After:

  RuntimeError: ("Name can't be blank", "Short name can't be blank")