Expose the response text of a 500 error when configuring a product version
This will make debugging easier since before this commit, it would just
show an ugly traceback with near the end of it:
RuntimeError: <Response [500]>