Fix showing diff for release brew_tags
Fixes the following error:

    ...
      File .../errata_tool_ansible/plugins/module_utils/common_errata_tool.py, line 208, in diff_settings
    TypeError: unhashable type: 'dict'

This is caused the fact that brew_tags passed to the module is simple
list of names, but the object returned by release API is in the
following form:

    "relationships": {
        "brew_tags": [
            {"id": 100, "name": "rhel-x.y-z-candidate"},
            {"id": 101, "name": "rhel-x.y-z-nocompose-candidate"},
        ],
        ...
    }